# @package _global_
up_sym: False
right_sym: False
regress_right: True
res: 2e-2
category: dishwasher
scale_range: [2.0, 3.2]
vote_range: [1.6, 1.6]
# scale_mean_all: [0.54, 0.71, 1.06]
scale_mean_base: [0.56, 0.65, 1.09]  
scale_mean_child: [0.56, 0.77, 1.08]
state: [-30,0] 